_wdt:
    resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
    prefix: /_wdt

_profiler:
    resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
    prefix: /_profiler

_errors:
    resource: '@TwigBundle/Resources/config/routing/errors.xml'
    prefix: /_error

_main:
    resource: routing.yml

faire_play_accueil:
    path: /index
    defaults:
        _controller: AppBundle:Advert:index

faire_play_nosProjets:
   path: /nos-projets
   defaults:
      _controller: AppBundle:Advert:nosprojets